#include "front_ir_bumper.h"
#include "cliff_ir.h"   /* publish the right-cliff demod (PA3) into the cliff model */

/* Front IR panel (J7) production acquisition engine.
 *
 * Characterization showed the emit->receive path is a BAND-PASS peaking at
 * ~1 kHz: the C34/Q11 AC coupling high-passes the emitter (kills <~250 Hz) and
 * the receiver phototransistor low-passes (kills >~4 kHz). So the carrier runs
 * continuously at 1 kHz and we detect it synchronously.
 *
 * Hardware datapath, no CPU in the sampling loop:
 *   - TIM2_CH3 (PB10) in TOGGLE mode flips every timer period. The timer runs
 *     at 2 kHz, so the toggled output is a clean 1 kHz, 50% carrier.
 *   - TIM2 TRGO = update (2 kHz) triggers the ADC. The update fires a quarter of
 *     a carrier period after each toggle, i.e. at the CENTRE of each carrier
 *     half -> every other ADC trigger lands in the LED-on vs LED-off half.
 *   - ADC scans all 8 reflective-IR sense lines on each trigger (3 front-panel
 *     zones F/L/R + 4 floor/cliff sensors + the left side transceiver); DMA1_Ch1
 *     (circular) stores the samples. All 8 share the one Q11 carrier.
 *   - Per channel, signal = mean(off-half) - mean(on-half): the carrier-locked
 *     reflected IR. Ambient (window/lamp/DC) is identical in two adjacent half
 *     periods, so it cancels. (Verified: carrier-off demod reads exactly 0.)
 *
 * This file is user-owned and is not generated by STM32CubeMX.
 */

/* TIM2 carrier configured by CubeMX MX_TIM2_Init (Output Compare CH3 "No Output"
 * toggle mode, 2 kHz timer -> 1 kHz carrier, TRGO = update -> ADC trigger).
 * "No Output" means CubeMX does not route the channel to PB10, so this driver
 * claims PB10 as TIM2_CH3 AF and starts the channel; HAL_TIM_OC_Start enables
 * the toggle output on PB10. */
#define FRONT_IR_CARRIER_CHANNEL TIM_CHANNEL_3

/* ADC scan: channels are converted in ascending channel-number order (forward
 * scan over CHSELR), so each DMA trigger stores the 13 samples in channel order
 * [PA1, PA2, PA3, PA5, PA7, PB0, PB1, PC0, PC1, PC2, PC3, PC4, PC5]. The 8 reflective IR
 * sense lines ride the one Q11/PB10 carrier and are demodulated (on-off). PA1
 * (ch1, 24V input/dock-rail sense), PA2 (ch2, battery voltage) and PA7 (ch7,
 * battery current from U4) are NOT carrier-modulated, so for them we publish the
 * plain MEAN of the half-buffer (the demod difference would be ~0). The two motor
 * VPROPI currents (PB1/ch9, PC5/ch15) are likewise published as plain MEANs. Pins
 * are ADC_INx in the .ioc (MspInit sets them analog); this engine scans all 13. */
#define FRONT_IR_VIN_ADC_CHANNEL     ADC_CHANNEL_1  /* 24V input/dock rail -> PA1 */
#define FRONT_IR_VBAT_ADC_CHANNEL    ADC_CHANNEL_2  /* battery voltage     -> PA2 */
#define FRONT_IR_RCLIFF_ADC_CHANNEL  ADC_CHANNEL_3  /* J2:4  right cliff   -> PA3 */
#define FRONT_IR_F_ADC_CHANNEL       ADC_CHANNEL_5  /* J7:6  F zone        -> PA5 */
#define FRONT_IR_BATT_ADC_CHANNEL    ADC_CHANNEL_7  /* U4 OUT2 batt current-> PA7 */
#define FRONT_IR_L_ADC_CHANNEL       ADC_CHANNEL_8  /* J7:7  L zone        -> PB0 */
#define FRONT_IR_MOTL_ADC_CHANNEL    ADC_CHANNEL_9  /* U2 pin15 VPROPI mot-L-> PB1 */
#define FRONT_IR_SIDE_ADC_CHANNEL    ADC_CHANNEL_10 /* J17:5 side IR TRX RX-> PC0 */
#define FRONT_IR_LCLIFF_ADC_CHANNEL  ADC_CHANNEL_11 /* J17:4 left cliff    -> PC1 */
#define FRONT_IR_FLCLIFF_ADC_CHANNEL ADC_CHANNEL_12 /* J4:3  front-L cliff -> PC2 */
#define FRONT_IR_R_ADC_CHANNEL       ADC_CHANNEL_13 /* J7:5  R zone        -> PC3 */
#define FRONT_IR_FRCLIFF_ADC_CHANNEL ADC_CHANNEL_14 /* J3:3  front-R cliff -> PC4 */
#define FRONT_IR_MOTR_ADC_CHANNEL    ADC_CHANNEL_15 /* U6 pin15 VPROPI mot-R-> PC5 */
/* Forward scan converts in ASCENDING channel number: 1,2,3,5,7,8,9,10,11,12,13,14,15. */
#define FRONT_IR_SCAN_CHANNELS 13U
#define FRONT_IR_IDX_VIN     0U  /* ch1  PA1 24V input/dock rail (MEAN) */
#define FRONT_IR_IDX_VBAT    1U  /* ch2  PA2 battery voltage (MEAN)  */
#define FRONT_IR_IDX_RCLIFF  2U  /* ch3  PA3 right cliff             */
#define FRONT_IR_IDX_F       3U  /* ch5  PA5 front-centre zone       */
#define FRONT_IR_IDX_BATT    4U  /* ch7  PA7 battery current (MEAN)  */
#define FRONT_IR_IDX_L       5U  /* ch8  PB0 front-left zone         */
#define FRONT_IR_IDX_MOTL    6U  /* ch9  PB1 motor-L VPROPI (MEAN)   */
#define FRONT_IR_IDX_SIDE    7U  /* ch10 PC0 left side IR transceiver*/
#define FRONT_IR_IDX_LCLIFF  8U  /* ch11 PC1 left cliff              */
#define FRONT_IR_IDX_FLCLIFF 9U  /* ch12 PC2 front-left cliff        */
#define FRONT_IR_IDX_R       10U /* ch13 PC3 front-right zone        */
#define FRONT_IR_IDX_FRCLIFF 11U /* ch14 PC4 front-right cliff       */
#define FRONT_IR_IDX_MOTR    12U /* ch15 PC5 motor-R VPROPI (MEAN)   */

/* One half-buffer = PERIODS_PER_HALF carrier periods. Each period = 2 ADC
 * triggers (on-half + off-half), each trigger = FRONT_IR_SCAN_CHANNELS samples.
 * DMA is circular over two halves; we demod the half the DMA is not writing. */
#define FRONT_IR_PERIODS_PER_HALF 64U
#define FRONT_IR_HALF_SAMPLES (FRONT_IR_PERIODS_PER_HALF * 2U * FRONT_IR_SCAN_CHANNELS)
#define FRONT_IR_BUF_SAMPLES (FRONT_IR_HALF_SAMPLES * 2U)

volatile uint16_t g_front_ir_r_on_adc = 0;
volatile uint16_t g_front_ir_f_on_adc = 0;
volatile uint16_t g_front_ir_l_on_adc = 0;
volatile uint16_t g_front_ir_r_off_adc = 0;
volatile uint16_t g_front_ir_f_off_adc = 0;
volatile uint16_t g_front_ir_l_off_adc = 0;
volatile int16_t g_front_ir_r_signal = 0;
volatile int16_t g_front_ir_f_signal = 0;
volatile int16_t g_front_ir_l_signal = 0;
/* Battery low-side current sense (PA7/ADC_IN7, U4 OUT2): raw 12-bit MEAN over the
 * last half-buffer (NOT carrier-demodulated). Convert with FrontIrBumper_BattMilliVolts. */
volatile uint16_t g_batt_isense_adc = 0;
/* Battery VOLTAGE sense (PA2/ADC_IN2): raw 12-bit MEAN over the last half-buffer
 * (NOT carrier-demodulated). Convert with FrontIrBumper_VbatPinMilliVolts. */
volatile uint16_t g_vbat_sense_adc = 0;
/* 24V INPUT / dock-rail sense (PA1/ADC_IN1): raw 12-bit MEAN. Same node as the
 * dock power (J10) through a diode-OR; divided down to the pin. Cal TBD. */
volatile uint16_t g_vin_sense_adc = 0;
/* Motor VPROPI current sense means (PB1/ch9 left, PC5/ch15 right), raw 12-bit. */
volatile uint16_t g_motor_l_isense_adc = 0;
volatile uint16_t g_motor_r_isense_adc = 0;
/* Rate of change of the reflected-IR signal per zone (this update minus the
 * previous, ~15 Hz). Positive = object getting closer / brightening
 * (approaching); negative = receding. Detects MOVING obstacles that a plain
 * present/absent threshold would miss (legs, dog, etc.). */
volatile int16_t g_front_ir_r_rate = 0;
volatile int16_t g_front_ir_f_rate = 0;
volatile int16_t g_front_ir_l_rate = 0;

static int16_t s_front_ir_r_prev = 0;
static int16_t s_front_ir_f_prev = 0;
static int16_t s_front_ir_l_prev = 0;

static ADC_HandleTypeDef *s_adc = NULL;
static TIM_HandleTypeDef *s_carrier_tim = NULL;
static DMA_HandleTypeDef s_hdma_adc;
static uint16_t s_adc_buf[FRONT_IR_BUF_SAMPLES];
static volatile uint8_t s_half_ready = 0; /* bit0: lower half, bit1: upper half */

static void FrontIrBumper_AdcDmaInit(void)
{
  ADC_ChannelConfTypeDef sConfig = {0};

  /* Re-init the ADC for hardware-triggered, DMA-fed circular scanning. */
  HAL_ADC_Stop(s_adc);
  s_adc->Init.ScanConvMode = ADC_SCAN_DIRECTION_FORWARD;
  s_adc->Init.ContinuousConvMode = DISABLE;
  s_adc->Init.DiscontinuousConvMode = DISABLE;
  s_adc->Init.ExternalTrigConv = ADC_EXTERNALTRIGCONV_T2_TRGO;
  s_adc->Init.ExternalTrigConvEdge = ADC_EXTERNALTRIGCONVEDGE_RISING;
  s_adc->Init.DMAContinuousRequests = ENABLE; /* unlimited requests for circular DMA */
  s_adc->Init.EOCSelection = ADC_EOC_SINGLE_CONV;
  (void)HAL_ADC_Init(s_adc);

  /* All analog sense pins (PA3, PA5, PB0, PC0..PC4) are declared as ADC_INx in
   * the .ioc and set to GPIO_MODE_ANALOG by the CubeMX-generated
   * HAL_ADC_MspInit, which already ran in MX_ADC_Init - nothing to do here. */

  /* Full 13-channel scan: 8 reflective-IR sense lines + battery current (ch7) +
   * both motor VPROPI currents (ch9/ch15). CHSELR converts in ascending channel
   * order, so e.g. PA7/ch7 lands at FRONT_IR_IDX_BATT, PB1/ch9 at IDX_MOTL. */
  s_adc->Instance->CHSELR = 0;
  sConfig.Rank = ADC_RANK_CHANNEL_NUMBER;
  sConfig.SamplingTime = ADC_SAMPLETIME_239CYCLES_5; /* low noise; 11ch ~198us << 500us trigger */
  sConfig.Channel = FRONT_IR_VIN_ADC_CHANNEL;
  (void)HAL_ADC_ConfigChannel(s_adc, &sConfig);
  sConfig.Channel = FRONT_IR_VBAT_ADC_CHANNEL;
  (void)HAL_ADC_ConfigChannel(s_adc, &sConfig);
  sConfig.Channel = FRONT_IR_RCLIFF_ADC_CHANNEL;
  (void)HAL_ADC_ConfigChannel(s_adc, &sConfig);
  sConfig.Channel = FRONT_IR_F_ADC_CHANNEL;
  (void)HAL_ADC_ConfigChannel(s_adc, &sConfig);
  sConfig.Channel = FRONT_IR_BATT_ADC_CHANNEL;
  (void)HAL_ADC_ConfigChannel(s_adc, &sConfig);
  sConfig.Channel = FRONT_IR_L_ADC_CHANNEL;
  (void)HAL_ADC_ConfigChannel(s_adc, &sConfig);
  sConfig.Channel = FRONT_IR_MOTL_ADC_CHANNEL;
  (void)HAL_ADC_ConfigChannel(s_adc, &sConfig);
  sConfig.Channel = FRONT_IR_SIDE_ADC_CHANNEL;
  (void)HAL_ADC_ConfigChannel(s_adc, &sConfig);
  sConfig.Channel = FRONT_IR_LCLIFF_ADC_CHANNEL;
  (void)HAL_ADC_ConfigChannel(s_adc, &sConfig);
  sConfig.Channel = FRONT_IR_FLCLIFF_ADC_CHANNEL;
  (void)HAL_ADC_ConfigChannel(s_adc, &sConfig);
  sConfig.Channel = FRONT_IR_R_ADC_CHANNEL;
  (void)HAL_ADC_ConfigChannel(s_adc, &sConfig);
  sConfig.Channel = FRONT_IR_FRCLIFF_ADC_CHANNEL;
  (void)HAL_ADC_ConfigChannel(s_adc, &sConfig);
  sConfig.Channel = FRONT_IR_MOTR_ADC_CHANNEL;
  (void)HAL_ADC_ConfigChannel(s_adc, &sConfig);

  /* DMA1_Channel1 <- ADC1, circular, half-word, memory-incrementing. */
  __HAL_RCC_DMA1_CLK_ENABLE();
  s_hdma_adc.Instance = DMA1_Channel1;
  s_hdma_adc.Init.Direction = DMA_PERIPH_TO_MEMORY;
  s_hdma_adc.Init.PeriphInc = DMA_PINC_DISABLE;
  s_hdma_adc.Init.MemInc = DMA_MINC_ENABLE;
  s_hdma_adc.Init.PeriphDataAlignment = DMA_PDATAALIGN_HALFWORD;
  s_hdma_adc.Init.MemDataAlignment = DMA_MDATAALIGN_HALFWORD;
  s_hdma_adc.Init.Mode = DMA_CIRCULAR;
  s_hdma_adc.Init.Priority = DMA_PRIORITY_HIGH;
  (void)HAL_DMA_Init(&s_hdma_adc);
  __HAL_LINKDMA(s_adc, DMA_Handle, s_hdma_adc);

  HAL_NVIC_SetPriority(DMA1_Channel1_IRQn, 2, 0);
  HAL_NVIC_EnableIRQ(DMA1_Channel1_IRQn);
}

/* CubeMX configures TIM2 in "No Output" mode, so it does not route CH3 to PB10.
 * Claim PB10 as TIM2_CH3 alternate function here; HAL_TIM_OC_Start then enables
 * the toggle output on it. */
static void FrontIrBumper_CarrierPinInit(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};

  __HAL_RCC_GPIOB_CLK_ENABLE();
  GPIO_InitStruct.Pin = GPIO_PIN_10; /* PB10 = FRONT_IR_Q11_PULSE = TIM2_CH3 */
  GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
  GPIO_InitStruct.Alternate = GPIO_AF2_TIM2;
  HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
}

void FrontIrBumper_Init(ADC_HandleTypeDef *receiver_adc, TIM_HandleTypeDef *carrier_tim)
{
  s_adc = receiver_adc;
  s_carrier_tim = carrier_tim;

  HAL_GPIO_WritePin(SWITCHED_SENSOR_5V_EN_GPIO_Port, SWITCHED_SENSOR_5V_EN_Pin, GPIO_PIN_SET);
  HAL_GPIO_WritePin(FRONT_IR_SENSOR_3V3_EN_GPIO_Port, FRONT_IR_SENSOR_3V3_EN_Pin, GPIO_PIN_SET);

  FrontIrBumper_CarrierPinInit();
  FrontIrBumper_AdcDmaInit();

  /* Arm the DMA acquisition (waits for the carrier's TRGO), then start the
   * carrier which drives PB10 and generates the ADC triggers. */
  (void)HAL_ADC_Start_DMA(s_adc, (uint32_t *)s_adc_buf, FRONT_IR_BUF_SAMPLES);
  (void)HAL_TIM_OC_Start(s_carrier_tim, FRONT_IR_CARRIER_CHANNEL);
}

/* Reduce one channel's two phase-accumulators to per-sample on/off means. Each
 * phase summed FRONT_IR_PERIODS_PER_HALF samples; the inverting path makes the
 * LED-on half read lower, so on = min(phase), off = max(phase). */
static void FrontIrBumper_LoHi(const int32_t *a, const int32_t *b, uint32_t idx,
                               uint16_t *lo, uint16_t *hi)
{
  int32_t av = a[idx];
  int32_t bv = b[idx];
  int32_t mn = (av < bv) ? av : bv;
  int32_t mx = (av > bv) ? av : bv;
  *lo = (uint16_t)(mn / (int32_t)FRONT_IR_PERIODS_PER_HALF);
  *hi = (uint16_t)(mx / (int32_t)FRONT_IR_PERIODS_PER_HALF);
}

/* Demodulate one half-buffer: split the FRONT_IR_PERIODS_PER_HALF*2 triggers
 * into the two carrier phases and reduce to per-channel on/off means. */
static void FrontIrBumper_DemodHalf(const uint16_t *half)
{
  int32_t a[FRONT_IR_SCAN_CHANNELS] = {0}; /* even triggers (one carrier phase) */
  int32_t b[FRONT_IR_SCAN_CHANNELS] = {0}; /* odd triggers (the other phase)    */
  const uint32_t triggers = FRONT_IR_PERIODS_PER_HALF * 2U;
  uint16_t lo, hi;

  for (uint32_t t = 0; t < triggers; t++)
  {
    const uint16_t *s = &half[t * FRONT_IR_SCAN_CHANNELS];
    int32_t *acc = (t & 1U) ? b : a;
    for (uint32_t c = 0; c < FRONT_IR_SCAN_CHANNELS; c++)
    {
      acc[c] += s[c];
    }
  }

  /* Front panel zones also expose the raw on/off ADC means (console/telemetry). */
  FrontIrBumper_LoHi(a, b, FRONT_IR_IDX_F, &lo, &hi);
  g_front_ir_f_on_adc = lo;
  g_front_ir_f_off_adc = hi;
  g_front_ir_f_signal = (int16_t)(hi - lo);
  FrontIrBumper_LoHi(a, b, FRONT_IR_IDX_L, &lo, &hi);
  g_front_ir_l_on_adc = lo;
  g_front_ir_l_off_adc = hi;
  g_front_ir_l_signal = (int16_t)(hi - lo);
  FrontIrBumper_LoHi(a, b, FRONT_IR_IDX_R, &lo, &hi);
  g_front_ir_r_on_adc = lo;
  g_front_ir_r_off_adc = hi;
  g_front_ir_r_signal = (int16_t)(hi - lo);

  /* The 4 cliff sensors + the left side IR transceiver ride the same Q11 carrier
   * and demodulate identically; publish each into the cliff model (CliffIr_Task
   * derives the per-channel rate). */
  FrontIrBumper_LoHi(a, b, FRONT_IR_IDX_RCLIFF, &lo, &hi);
  CliffIr_SetSignal(CLIFF_RIGHT, (int16_t)(hi - lo));
  FrontIrBumper_LoHi(a, b, FRONT_IR_IDX_LCLIFF, &lo, &hi);
  CliffIr_SetSignal(CLIFF_LEFT, (int16_t)(hi - lo));
  FrontIrBumper_LoHi(a, b, FRONT_IR_IDX_FLCLIFF, &lo, &hi);
  CliffIr_SetSignal(CLIFF_FRONT_L, (int16_t)(hi - lo));
  FrontIrBumper_LoHi(a, b, FRONT_IR_IDX_FRCLIFF, &lo, &hi);
  CliffIr_SetSignal(CLIFF_FRONT_R, (int16_t)(hi - lo));
  FrontIrBumper_LoHi(a, b, FRONT_IR_IDX_SIDE, &lo, &hi);
  CliffIr_SetSignal(SIDE_IR, (int16_t)(hi - lo));

  /* Battery current (PA7) is not carrier-modulated, so publish the plain MEAN of
     the whole half-buffer (both phases) = raw 12-bit ADC count at PA7. */
  g_batt_isense_adc = (uint16_t)((a[FRONT_IR_IDX_BATT] + b[FRONT_IR_IDX_BATT])
                                 / (int32_t)(2U * FRONT_IR_PERIODS_PER_HALF));

  /* Battery voltage (PA2): same plain MEAN (not carrier-modulated). */
  g_vbat_sense_adc = (uint16_t)((a[FRONT_IR_IDX_VBAT] + b[FRONT_IR_IDX_VBAT])
                                / (int32_t)(2U * FRONT_IR_PERIODS_PER_HALF));

  /* 24V input / dock-rail voltage (PA1): same plain MEAN. */
  g_vin_sense_adc = (uint16_t)((a[FRONT_IR_IDX_VIN] + b[FRONT_IR_IDX_VIN])
                               / (int32_t)(2U * FRONT_IR_PERIODS_PER_HALF));

  /* Motor VPROPI currents (PB1/ch9, PC5/ch15): plain MEAN, not carrier-modulated. */
  g_motor_l_isense_adc = (uint16_t)((a[FRONT_IR_IDX_MOTL] + b[FRONT_IR_IDX_MOTL])
                                    / (int32_t)(2U * FRONT_IR_PERIODS_PER_HALF));
  g_motor_r_isense_adc = (uint16_t)((a[FRONT_IR_IDX_MOTR] + b[FRONT_IR_IDX_MOTR])
                                    / (int32_t)(2U * FRONT_IR_PERIODS_PER_HALF));

  /* Approach detection: change vs previous update. */
  g_front_ir_f_rate = (int16_t)(g_front_ir_f_signal - s_front_ir_f_prev);
  g_front_ir_l_rate = (int16_t)(g_front_ir_l_signal - s_front_ir_l_prev);
  g_front_ir_r_rate = (int16_t)(g_front_ir_r_signal - s_front_ir_r_prev);
  s_front_ir_f_prev = g_front_ir_f_signal;
  s_front_ir_l_prev = g_front_ir_l_signal;
  s_front_ir_r_prev = g_front_ir_r_signal;
}

void FrontIrBumper_SetIllumination(int on)
{
  if (s_carrier_tim == NULL)
  {
    return;
  }
  if (on)
  {
    FrontIrBumper_CarrierPinInit();                 /* PB10 -> TIM2_CH3 AF */
    (void)HAL_TIM_OC_Start(s_carrier_tim, FRONT_IR_CARRIER_CHANNEL);
  }
  else
  {
    GPIO_InitTypeDef g = {0};
    (void)HAL_TIM_OC_Stop(s_carrier_tim, FRONT_IR_CARRIER_CHANNEL);
    /* drive PB10 (Q11) low so the carrier is fully off (AC-coupled emitters die) */
    __HAL_RCC_GPIOB_CLK_ENABLE();
    g.Pin = GPIO_PIN_10;
    g.Mode = GPIO_MODE_OUTPUT_PP;
    g.Pull = GPIO_NOPULL;
    g.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOB, &g);
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET);
  }
}

void FrontIrBumper_Task(void)
{
  uint8_t ready = s_half_ready;

  if (ready & 0x01U)
  {
    s_half_ready &= (uint8_t)~0x01U;
    FrontIrBumper_DemodHalf(&s_adc_buf[0]);
  }
  if (ready & 0x02U)
  {
    s_half_ready &= (uint8_t)~0x02U;
    FrontIrBumper_DemodHalf(&s_adc_buf[FRONT_IR_HALF_SAMPLES]);
  }
}

/* DMA half/complete -> flag the stable half for the main loop to demodulate. */
void HAL_ADC_ConvHalfCpltCallback(ADC_HandleTypeDef *hadc)
{
  if (hadc == s_adc)
  {
    s_half_ready |= 0x01U; /* lower half filled */
  }
}

void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
{
  if (hadc == s_adc)
  {
    s_half_ready |= 0x02U; /* upper half filled */
  }
}

void DMA1_Channel1_IRQHandler(void)
{
  HAL_DMA_IRQHandler(&s_hdma_adc);
}
