#include "front_ir_bumper.h"

/* Front IR panel (J7) production acquisition engine.
 *
 * Characterization showed the emit->receive path is a BAND-PASS peaking at
 * ~1 kHz: the C34/Q11 AC coupling high-passes the emitter (kills <~250 Hz) and
 * the receiver phototransistor low-passes (kills >~4 kHz). So the carrier runs
 * continuously at 1 kHz and we detect it synchronously.
 *
 * Hardware datapath, no CPU in the sampling loop:
 *   - TIM2_CH3 (PB10) in TOGGLE mode flips every timer period. The timer runs
 *     at 2 kHz, so the toggled output is a clean 1 kHz, 50% carrier.
 *   - TIM2 TRGO = update (2 kHz) triggers the ADC. The update fires a quarter of
 *     a carrier period after each toggle, i.e. at the CENTRE of each carrier
 *     half -> every other ADC trigger lands in the LED-on vs LED-off half.
 *   - ADC scans F/L/R on each trigger; DMA1_Ch1 (circular) stores the samples.
 *   - Per channel, signal = mean(off-half) - mean(on-half): the carrier-locked
 *     reflected IR. Ambient (window/lamp/DC) is identical in two adjacent half
 *     periods, so it cancels. (Verified: carrier-off demod reads exactly 0.)
 *
 * This file is user-owned and is not generated by STM32CubeMX.
 */

/* TIM2 carrier configured by CubeMX MX_TIM2_Init (Output Compare CH3 "No Output"
 * toggle mode, 2 kHz timer -> 1 kHz carrier, TRGO = update -> ADC trigger).
 * "No Output" means CubeMX does not route the channel to PB10, so this driver
 * claims PB10 as TIM2_CH3 AF and starts the channel; HAL_TIM_OC_Start enables
 * the toggle output on PB10. */
#define FRONT_IR_CARRIER_CHANNEL TIM_CHANNEL_3

/* ADC scan: channels are converted in ascending channel-number order (forward
 * scan), so each DMA trigger stores [F, L, R]. */
#define FRONT_IR_R_ADC_CHANNEL ADC_CHANNEL_13 /* J7-5 R -> PC3 */
#define FRONT_IR_F_ADC_CHANNEL ADC_CHANNEL_5  /* J7-6 F -> PA5 */
#define FRONT_IR_L_ADC_CHANNEL ADC_CHANNEL_8  /* J7-7 L -> PB0 */
#define FRONT_IR_SCAN_CHANNELS 3U
#define FRONT_IR_IDX_F 0U
#define FRONT_IR_IDX_L 1U
#define FRONT_IR_IDX_R 2U

/* One half-buffer = PERIODS_PER_HALF carrier periods. Each period = 2 ADC
 * triggers (on-half + off-half), each trigger = FRONT_IR_SCAN_CHANNELS samples.
 * DMA is circular over two halves; we demod the half the DMA is not writing. */
#define FRONT_IR_PERIODS_PER_HALF 64U
#define FRONT_IR_HALF_SAMPLES (FRONT_IR_PERIODS_PER_HALF * 2U * FRONT_IR_SCAN_CHANNELS)
#define FRONT_IR_BUF_SAMPLES (FRONT_IR_HALF_SAMPLES * 2U)

volatile uint16_t g_front_ir_r_on_adc = 0;
volatile uint16_t g_front_ir_f_on_adc = 0;
volatile uint16_t g_front_ir_l_on_adc = 0;
volatile uint16_t g_front_ir_r_off_adc = 0;
volatile uint16_t g_front_ir_f_off_adc = 0;
volatile uint16_t g_front_ir_l_off_adc = 0;
volatile int16_t g_front_ir_r_signal = 0;
volatile int16_t g_front_ir_f_signal = 0;
volatile int16_t g_front_ir_l_signal = 0;
/* Rate of change of the reflected-IR signal per zone (this update minus the
 * previous, ~15 Hz). Positive = object getting closer / brightening
 * (approaching); negative = receding. Detects MOVING obstacles that a plain
 * present/absent threshold would miss (legs, dog, etc.). */
volatile int16_t g_front_ir_r_rate = 0;
volatile int16_t g_front_ir_f_rate = 0;
volatile int16_t g_front_ir_l_rate = 0;

static int16_t s_front_ir_r_prev = 0;
static int16_t s_front_ir_f_prev = 0;
static int16_t s_front_ir_l_prev = 0;

static ADC_HandleTypeDef *s_adc = NULL;
static TIM_HandleTypeDef *s_carrier_tim = NULL;
static DMA_HandleTypeDef s_hdma_adc;
static uint16_t s_adc_buf[FRONT_IR_BUF_SAMPLES];
static volatile uint8_t s_half_ready = 0; /* bit0: lower half, bit1: upper half */

static void FrontIrBumper_AdcDmaInit(void)
{
  ADC_ChannelConfTypeDef sConfig = {0};

  /* Re-init the ADC for hardware-triggered, DMA-fed circular scanning. */
  HAL_ADC_Stop(s_adc);
  s_adc->Init.ScanConvMode = ADC_SCAN_DIRECTION_FORWARD;
  s_adc->Init.ContinuousConvMode = DISABLE;
  s_adc->Init.DiscontinuousConvMode = DISABLE;
  s_adc->Init.ExternalTrigConv = ADC_EXTERNALTRIGCONV_T2_TRGO;
  s_adc->Init.ExternalTrigConvEdge = ADC_EXTERNALTRIGCONVEDGE_RISING;
  s_adc->Init.DMAContinuousRequests = ENABLE; /* unlimited requests for circular DMA */
  s_adc->Init.EOCSelection = ADC_EOC_SINGLE_CONV;
  (void)HAL_ADC_Init(s_adc);

  /* Select exactly F, L, R (drop the motor-current channels for this engine). */
  s_adc->Instance->CHSELR = 0;
  sConfig.Rank = ADC_RANK_CHANNEL_NUMBER;
  sConfig.SamplingTime = ADC_SAMPLETIME_239CYCLES_5; /* long sample = low noise; 3ch ~54us << 500us */
  sConfig.Channel = FRONT_IR_F_ADC_CHANNEL;
  (void)HAL_ADC_ConfigChannel(s_adc, &sConfig);
  sConfig.Channel = FRONT_IR_L_ADC_CHANNEL;
  (void)HAL_ADC_ConfigChannel(s_adc, &sConfig);
  sConfig.Channel = FRONT_IR_R_ADC_CHANNEL;
  (void)HAL_ADC_ConfigChannel(s_adc, &sConfig);

  /* DMA1_Channel1 <- ADC1, circular, half-word, memory-incrementing. */
  __HAL_RCC_DMA1_CLK_ENABLE();
  s_hdma_adc.Instance = DMA1_Channel1;
  s_hdma_adc.Init.Direction = DMA_PERIPH_TO_MEMORY;
  s_hdma_adc.Init.PeriphInc = DMA_PINC_DISABLE;
  s_hdma_adc.Init.MemInc = DMA_MINC_ENABLE;
  s_hdma_adc.Init.PeriphDataAlignment = DMA_PDATAALIGN_HALFWORD;
  s_hdma_adc.Init.MemDataAlignment = DMA_MDATAALIGN_HALFWORD;
  s_hdma_adc.Init.Mode = DMA_CIRCULAR;
  s_hdma_adc.Init.Priority = DMA_PRIORITY_HIGH;
  (void)HAL_DMA_Init(&s_hdma_adc);
  __HAL_LINKDMA(s_adc, DMA_Handle, s_hdma_adc);

  HAL_NVIC_SetPriority(DMA1_Channel1_IRQn, 2, 0);
  HAL_NVIC_EnableIRQ(DMA1_Channel1_IRQn);
}

/* CubeMX configures TIM2 in "No Output" mode, so it does not route CH3 to PB10.
 * Claim PB10 as TIM2_CH3 alternate function here; HAL_TIM_OC_Start then enables
 * the toggle output on it. */
static void FrontIrBumper_CarrierPinInit(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};

  __HAL_RCC_GPIOB_CLK_ENABLE();
  GPIO_InitStruct.Pin = GPIO_PIN_10; /* PB10 = FRONT_IR_Q11_PULSE = TIM2_CH3 */
  GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
  GPIO_InitStruct.Alternate = GPIO_AF2_TIM2;
  HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
}

void FrontIrBumper_Init(ADC_HandleTypeDef *receiver_adc, TIM_HandleTypeDef *carrier_tim)
{
  s_adc = receiver_adc;
  s_carrier_tim = carrier_tim;

  HAL_GPIO_WritePin(SWITCHED_SENSOR_5V_EN_GPIO_Port, SWITCHED_SENSOR_5V_EN_Pin, GPIO_PIN_SET);
  HAL_GPIO_WritePin(FRONT_IR_SENSOR_3V3_EN_GPIO_Port, FRONT_IR_SENSOR_3V3_EN_Pin, GPIO_PIN_SET);

  FrontIrBumper_CarrierPinInit();
  FrontIrBumper_AdcDmaInit();

  /* Arm the DMA acquisition (waits for the carrier's TRGO), then start the
   * carrier which drives PB10 and generates the ADC triggers. */
  (void)HAL_ADC_Start_DMA(s_adc, (uint32_t *)s_adc_buf, FRONT_IR_BUF_SAMPLES);
  (void)HAL_TIM_OC_Start(s_carrier_tim, FRONT_IR_CARRIER_CHANNEL);
}

/* Demodulate one half-buffer: split the FRONT_IR_PERIODS_PER_HALF*2 triggers
 * into the two carrier phases and reduce to per-channel on/off means. */
static void FrontIrBumper_DemodHalf(const uint16_t *half)
{
  int32_t a[FRONT_IR_SCAN_CHANNELS] = {0}; /* even triggers (one carrier phase) */
  int32_t b[FRONT_IR_SCAN_CHANNELS] = {0}; /* odd triggers (the other phase)    */
  const uint32_t triggers = FRONT_IR_PERIODS_PER_HALF * 2U;

  for (uint32_t t = 0; t < triggers; t++)
  {
    const uint16_t *s = &half[t * FRONT_IR_SCAN_CHANNELS];
    int32_t *acc = (t & 1U) ? b : a;
    acc[FRONT_IR_IDX_F] += s[FRONT_IR_IDX_F];
    acc[FRONT_IR_IDX_L] += s[FRONT_IR_IDX_L];
    acc[FRONT_IR_IDX_R] += s[FRONT_IR_IDX_R];
  }

  /* Each phase has FRONT_IR_PERIODS_PER_HALF samples. The inverting path makes
   * the LED-on half read lower, so on = min(phase), off = max(phase). */
  uint16_t f_lo = (uint16_t)((a[FRONT_IR_IDX_F] < b[FRONT_IR_IDX_F] ? a[FRONT_IR_IDX_F] : b[FRONT_IR_IDX_F]) / (int32_t)FRONT_IR_PERIODS_PER_HALF);
  uint16_t f_hi = (uint16_t)((a[FRONT_IR_IDX_F] > b[FRONT_IR_IDX_F] ? a[FRONT_IR_IDX_F] : b[FRONT_IR_IDX_F]) / (int32_t)FRONT_IR_PERIODS_PER_HALF);
  uint16_t l_lo = (uint16_t)((a[FRONT_IR_IDX_L] < b[FRONT_IR_IDX_L] ? a[FRONT_IR_IDX_L] : b[FRONT_IR_IDX_L]) / (int32_t)FRONT_IR_PERIODS_PER_HALF);
  uint16_t l_hi = (uint16_t)((a[FRONT_IR_IDX_L] > b[FRONT_IR_IDX_L] ? a[FRONT_IR_IDX_L] : b[FRONT_IR_IDX_L]) / (int32_t)FRONT_IR_PERIODS_PER_HALF);
  uint16_t r_lo = (uint16_t)((a[FRONT_IR_IDX_R] < b[FRONT_IR_IDX_R] ? a[FRONT_IR_IDX_R] : b[FRONT_IR_IDX_R]) / (int32_t)FRONT_IR_PERIODS_PER_HALF);
  uint16_t r_hi = (uint16_t)((a[FRONT_IR_IDX_R] > b[FRONT_IR_IDX_R] ? a[FRONT_IR_IDX_R] : b[FRONT_IR_IDX_R]) / (int32_t)FRONT_IR_PERIODS_PER_HALF);

  g_front_ir_f_on_adc = f_lo;
  g_front_ir_f_off_adc = f_hi;
  g_front_ir_f_signal = (int16_t)(f_hi - f_lo);
  g_front_ir_l_on_adc = l_lo;
  g_front_ir_l_off_adc = l_hi;
  g_front_ir_l_signal = (int16_t)(l_hi - l_lo);
  g_front_ir_r_on_adc = r_lo;
  g_front_ir_r_off_adc = r_hi;
  g_front_ir_r_signal = (int16_t)(r_hi - r_lo);

  /* Approach detection: change vs previous update. */
  g_front_ir_f_rate = (int16_t)(g_front_ir_f_signal - s_front_ir_f_prev);
  g_front_ir_l_rate = (int16_t)(g_front_ir_l_signal - s_front_ir_l_prev);
  g_front_ir_r_rate = (int16_t)(g_front_ir_r_signal - s_front_ir_r_prev);
  s_front_ir_f_prev = g_front_ir_f_signal;
  s_front_ir_l_prev = g_front_ir_l_signal;
  s_front_ir_r_prev = g_front_ir_r_signal;
}

void FrontIrBumper_Task(void)
{
  uint8_t ready = s_half_ready;

  if (ready & 0x01U)
  {
    s_half_ready &= (uint8_t)~0x01U;
    FrontIrBumper_DemodHalf(&s_adc_buf[0]);
  }
  if (ready & 0x02U)
  {
    s_half_ready &= (uint8_t)~0x02U;
    FrontIrBumper_DemodHalf(&s_adc_buf[FRONT_IR_HALF_SAMPLES]);
  }
}

/* DMA half/complete -> flag the stable half for the main loop to demodulate. */
void HAL_ADC_ConvHalfCpltCallback(ADC_HandleTypeDef *hadc)
{
  if (hadc == s_adc)
  {
    s_half_ready |= 0x01U; /* lower half filled */
  }
}

void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
{
  if (hadc == s_adc)
  {
    s_half_ready |= 0x02U; /* upper half filled */
  }
}

void DMA1_Channel1_IRQHandler(void)
{
  HAL_DMA_IRQHandler(&s_hdma_adc);
}
