/**
  ******************************************************************************
  * @file    console.h
  * @brief   Non-blocking UART console on USART1 (JP1 / PA9-PA10, 926000 8N1).
  *          RX: circular DMA ring drained by polling. TX: software ring drained
  *          by the USART1 TXE interrupt. No blocking HAL_UART_Transmit/HAL_Delay.
  *
  *          User-owned, not generated by CubeMX. Ported from the loading-stand
  *          console (single port here instead of the dual VCP+header version).
  ******************************************************************************
  */
#ifndef CONSOLE_H
#define CONSOLE_H

#include <stdint.h>
#include <stdbool.h>

#define CONSOLE_NPORT  1              /* single console on USART1                 */
#define CONSOLE_BOTH  (-1)           /* route output to every port (== port 0)   */

void Console_Init(void);              /* start RX DMA + TX IRQ                     */
void Console_Route(int port);         /* set output target: 0 or CONSOLE_BOTH     */
void Console_Print(const char *s);    /* enqueue a response                       */
void Console_Stream(const char *s);   /* enqueue telemetry, dropped if near full  */
bool Console_ReadByte(uint8_t *c, int *port);  /* pop a byte + its source port    */
void Console_UartIrq(void *huart);    /* call from USART1_IRQHandler              */

#endif /* CONSOLE_H */
