/* USER CODE BEGIN Header */
/*
 * Front IR navigation panel (J7) bring-up driver.
 *
 * Three front zones (R/F/L) are sensed by synchronous "lock-in" detection:
 * the Q11/PB10 IR carrier is gated ON/OFF many times per measurement and the
 * receiver ADC is sampled in both phases. signal = OFF - ON cancels ambient
 * light (window/room); only the modulated, reflected IR survives the
 * difference. The optical path is inverting (more reflected IR -> lower ADC
 * during ON), so OFF - ON grows positive as an obstacle gets closer.
 *
 * This file is user-owned and is not generated by STM32CubeMX.
 */
/* USER CODE END Header */

#ifndef FRONT_IR_BUMPER_H
#define FRONT_IR_BUMPER_H

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"
#include <stdbool.h>
#include <stdint.h>

typedef struct
{
  uint16_t vin_raw;
  uint16_t vbat_raw;
  uint16_t current_raw;
  uint16_t dma_index;
} FrontIrPowerSnapshot;

/* Averaged carrier-ON / carrier-OFF ADC levels per zone (R/F/L). */
extern volatile uint16_t g_front_ir_r_on_adc;
extern volatile uint16_t g_front_ir_f_on_adc;
extern volatile uint16_t g_front_ir_l_on_adc;
extern volatile uint16_t g_front_ir_r_off_adc;
extern volatile uint16_t g_front_ir_f_off_adc;
extern volatile uint16_t g_front_ir_l_off_adc;

/* Background-free reflected-IR signal per zone = OFF - ON (grows with obstacle). */
extern volatile int16_t g_front_ir_r_signal;
extern volatile int16_t g_front_ir_f_signal;
extern volatile int16_t g_front_ir_l_signal;

/* Per-zone rate of change of the signal (~15 Hz): + approaching, - receding. */
extern volatile int16_t g_front_ir_r_rate;
extern volatile int16_t g_front_ir_f_rate;
extern volatile int16_t g_front_ir_l_rate;

/* Battery low-side current sense at PA7/ADC_IN7 (U4 OUT2). Raw 12-bit MEAN of the
 * half-buffer - NOT carrier-demodulated. Use the helper for millivolts at the pin. */
extern volatile uint16_t g_batt_isense_adc;

/* Convert the PA7 raw ADC count to millivolts (12-bit, 3.3 V Vref). */
static inline uint16_t FrontIrBumper_BattMilliVolts(void)
{
  return (uint16_t)(((uint32_t)g_batt_isense_adc * 3300U) / 4095U);
}

/* Battery current in mA from the PA7 voltage. 4-point bench calibration
 * (2026-06-24): mV = 1180 + 488*I[A]  =>  I[mA] = (mV - 1180) * 1000 / 488.
 * 1180 mV = ~0 A offset (U4 A1 reference); positive = pack discharge,
 * negative = charge. Keep the sign all the way to Modbus/HA. */
#define BATT_ISENSE_OFFSET_MV 1180
#define BATT_ISENSE_MV_PER_A  488
static inline int16_t FrontIrBumper_BattMilliAmpsSigned(void)
{
  int32_t mv = (int32_t)FrontIrBumper_BattMilliVolts();
  int32_t ma = ((mv - BATT_ISENSE_OFFSET_MV) * 1000) / BATT_ISENSE_MV_PER_A;
  if (ma > 32767) ma = 32767;
  if (ma < -32768) ma = -32768;
  return (int16_t)ma;
}
static inline int FrontIrBumper_BattMilliAmps(void)
{
  int ma = (int)FrontIrBumper_BattMilliAmpsSigned();
  return (ma < 0) ? 0 : ma;
}

/* Motor low-side current sense via DRV8801 VPROPI: L = PB1/ADC_IN9 (U2 pin 15),
 * R = PC5/ADC_IN15 (U6 pin 15). Raw 12-bit MEAN of the half-buffer (NOT carrier-
 * demodulated). VPROPI is duty-weighted and falls to 0 V during slow-decay
 * recirculation, so this is the average active-drive current sense, not a peak.
 * Helper gives millivolts at the pin; amps cal (VPROPI gain x Rsense) is TBD. */
extern volatile uint16_t g_motor_l_isense_adc;
extern volatile uint16_t g_motor_r_isense_adc;
static inline uint16_t FrontIrBumper_MotorLMilliVolts(void)
{
  return (uint16_t)(((uint32_t)g_motor_l_isense_adc * 3300U) / 4095U);
}
static inline uint16_t FrontIrBumper_MotorRMilliVolts(void)
{
  return (uint16_t)(((uint32_t)g_motor_r_isense_adc * 3300U) / 4095U);
}

/* Battery VOLTAGE sense at PA2/ADC_IN2 (likely a divider from the pack). Raw
 * 12-bit MEAN; this returns the millivolts AT THE PIN. Pack-voltage calibration
 * (divider ratio) is TBD - user will supply real input values. */
extern volatile uint16_t g_vbat_sense_adc;
static inline uint16_t FrontIrBumper_VbatPinMilliVolts(void)
{
  return (uint16_t)(((uint32_t)g_vbat_sense_adc * 3300U) / 4095U);
}

/* Battery PACK voltage from the PA2 pin reading. Resistive divider (no offset),
 * cal 2026-06-24 from the flashed ADC: 14.47 V pack = 1481 mV pin => ratio x9.770
 * (same 71.5k/8.2k divider as VIN). V_pack = V_pin * 14470 / 1481. Pack mV. */
#define VBAT_CAL_PIN_MV  1481
#define VBAT_CAL_PACK_MV 14470
static inline uint32_t FrontIrBumper_VbatPackMilliVolts(void)
{
  return ((uint32_t)FrontIrBumper_VbatPinMilliVolts() * VBAT_CAL_PACK_MV) / VBAT_CAL_PIN_MV;
}

/* 24V input / dock-rail sense at PA1/ADC_IN1 (same node as dock power J10 via a
 * diode-OR; divided to the pin). Returns millivolts AT THE PIN; rail-voltage
 * calibration (divider + diode drop) is TBD. */
extern volatile uint16_t g_vin_sense_adc;
static inline uint16_t FrontIrBumper_VinPinMilliVolts(void)
{
  return (uint16_t)(((uint32_t)g_vin_sense_adc * 3300U) / 4095U);
}

/* 24V-rail voltage from the PA1 pin reading. Hardware divider (board markings):
 * top 71.5k (7152, to Vin) + bottom 8.2k (8201, to GND) => rail = pin * 79.7/8.2.
 * On dock this rail = V(J10) - one diode drop. Returns millivolts of the rail. */
#define VIN_DIV_NUM 797   /* (71.5k + 8.2k) scaled x10 */
#define VIN_DIV_DEN 82    /* 8.2k scaled x10 */
static inline uint32_t FrontIrBumper_VinRailMilliVolts(void)
{
  return ((uint32_t)FrontIrBumper_VinPinMilliVolts() * VIN_DIV_NUM) / VIN_DIV_DEN;
}

/* Fast 4 ms power snapshot from the already-running 2 kHz ADC DMA ring. */
bool FrontIrBumper_GetPowerSnapshot(FrontIrPowerSnapshot *snapshot);

/* Powers the sensor rails, starts the IR carrier (TIM2_CH3 on PB10) and arms the
 * DMA acquisition. receiver_adc is the ADC wired to the J7 R/F/L inputs;
 * carrier_tim is TIM2 (CubeMX: Output Compare CH3 toggle, TRGO = update). */
void FrontIrBumper_Init(ADC_HandleTypeDef *receiver_adc, TIM_HandleTypeDef *carrier_tim);

/* Run once per main-loop iteration; performs one lock-in measurement per period. */
void FrontIrBumper_Task(void);

/* Enable/disable the Q11 IR carrier (PB10). on=1 runs the 1 kHz carrier (normal);
 * on=0 stops it and holds PB10 low, killing the IR illumination - used to test
 * which emitters are fed from the shared Q11 illumination. */
void FrontIrBumper_SetIllumination(int on);

#ifdef __cplusplus
}
#endif

#endif /* FRONT_IR_BUMPER_H */
