/* USER CODE BEGIN Header */
/*
 * Front IR navigation panel (J7) bring-up driver.
 *
 * Three front zones (R/F/L) are sensed by synchronous "lock-in" detection:
 * the Q11/PB10 IR carrier is gated ON/OFF many times per measurement and the
 * receiver ADC is sampled in both phases. signal = OFF - ON cancels ambient
 * light (window/room); only the modulated, reflected IR survives the
 * difference. The optical path is inverting (more reflected IR -> lower ADC
 * during ON), so OFF - ON grows positive as an obstacle gets closer.
 *
 * This file is user-owned and is not generated by STM32CubeMX.
 */
/* USER CODE END Header */

#ifndef FRONT_IR_BUMPER_H
#define FRONT_IR_BUMPER_H

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"
#include <stdint.h>

/* Averaged carrier-ON / carrier-OFF ADC levels per zone (R/F/L). */
extern volatile uint16_t g_front_ir_r_on_adc;
extern volatile uint16_t g_front_ir_f_on_adc;
extern volatile uint16_t g_front_ir_l_on_adc;
extern volatile uint16_t g_front_ir_r_off_adc;
extern volatile uint16_t g_front_ir_f_off_adc;
extern volatile uint16_t g_front_ir_l_off_adc;

/* Background-free reflected-IR signal per zone = OFF - ON (grows with obstacle). */
extern volatile int16_t g_front_ir_r_signal;
extern volatile int16_t g_front_ir_f_signal;
extern volatile int16_t g_front_ir_l_signal;

/* Per-zone rate of change of the signal (~15 Hz): + approaching, - receding. */
extern volatile int16_t g_front_ir_r_rate;
extern volatile int16_t g_front_ir_f_rate;
extern volatile int16_t g_front_ir_l_rate;

/* Powers the sensor rails, starts the IR carrier (TIM2_CH3 on PB10) and arms the
 * DMA acquisition. receiver_adc is the ADC wired to the J7 R/F/L inputs;
 * carrier_tim is TIM2 (CubeMX: Output Compare CH3 toggle, TRGO = update). */
void FrontIrBumper_Init(ADC_HandleTypeDef *receiver_adc, TIM_HandleTypeDef *carrier_tim);

/* Run once per main-loop iteration; performs one lock-in measurement per period. */
void FrontIrBumper_Task(void);

#ifdef __cplusplus
}
#endif

#endif /* FRONT_IR_BUMPER_H */
