/* USER CODE BEGIN Header */
/*
 * Left wheel motor bring-up controller.
 * This file is user-owned and is not generated by STM32CubeMX.
 */
/* USER CODE END Header */

#ifndef MOTOR_CONTROL_H
#define MOTOR_CONTROL_H

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"
#include <stdint.h>

typedef enum
{
  MOTOR_CONTROL_MODE_OFF = 0,
  MOTOR_CONTROL_MODE_SPEED,
  MOTOR_CONTROL_MODE_POSITION
} MotorControlMode;

typedef enum
{
  MOTOR_LEFT = 0,
  MOTOR_RIGHT = 1
} MotorSide;

/* Runtime state of one wheel, derived live (display/diagnostics, not control). */
typedef enum
{
  MOTOR_STATE_IDLE = 0,   /* not commanded (mode OFF)                          */
  MOTOR_STATE_RUNNING,    /* commanded and turning                             */
  MOTOR_STATE_STALLED,    /* commanded with drive applied but not turning      */
  MOTOR_STATE_FAULT       /* driver nFAULT held low (OCP / UVLO / thermal)     */
} MotorState;

/* Complete single-point snapshot of one wheel: control state, encoder odometry +
 * speed, the applied PWM, the VPROPI current sense, and the driver-fault latch. */
typedef struct
{
  MotorState       state;
  MotorControlMode mode;
  int32_t          position_edges;
  float            position_rev;
  int32_t          speed_edges_per_s;   /* speed from the encoder */
  float            speed_rpm;           /* same, in wheel rpm     */
  int16_t          pwm_command;         /* signed applied PWM (sign = direction) */
  uint16_t         current_adc;         /* VPROPI raw 12-bit (L=PB1/ch9, R=PC5/ch15) */
  uint16_t         current_mv;          /* VPROPI millivolts at the pin */
  uint32_t         edge_count;
  uint8_t          encoder_level;
  uint8_t          fault_active;   /* nFAULT currently held low (debounced)    */
  uint8_t          fault_latched;  /* sticky since boot / last ClearFault      */
  uint32_t         fault_count;    /* high->low fault edges (e.g. OCP retries) */
} MotorStatus;

typedef struct
{
  int32_t position_edges;
  int32_t target_position_edges;
  int32_t speed_edges_per_s;
  int32_t target_speed_edges_per_s;
  float position_rev;
  float target_position_rev;
  float speed_rpm;
  float target_speed_rpm;
  float position_m;
  float target_position_m;
  float speed_mps;
  float target_speed_mps;
  int16_t pwm_command;
  uint32_t edge_count;
  uint8_t encoder_level;
  uint8_t fault_active;
  MotorControlMode mode;
} MotorControlStatus;

extern volatile int32_t g_motor_l_position_edges;
extern volatile int32_t g_motor_l_speed_edges_per_s;
extern volatile uint32_t g_motor_l_enc_edges;
extern volatile uint8_t g_motor_l_enc_level;
extern volatile int16_t g_motor_l_pwm_command;
extern volatile int32_t g_motor_r_position_edges;
extern volatile int32_t g_motor_r_speed_edges_per_s;
extern volatile uint32_t g_motor_r_enc_edges;
extern volatile uint8_t g_motor_r_enc_level;
extern volatile int16_t g_motor_r_pwm_command;

void MotorControl_Init(TIM_HandleTypeDef *pwm_timer, ADC_HandleTypeDef *current_adc);
void MotorControl_OnEncoderEdge(uint16_t pin); /* EXTI dispatch hook (called from main.c) */
void MotorControl_Task(void);
void MotorControl_Stop(void);
void MotorControl_SetRightTestPwm(int16_t signed_pwm);
uint8_t MotorControl_IsRightBusy(void);
void MotorControl_SetSpeed(int32_t speed_edges_per_s);
void MotorControl_SetWheelSpeed(float speed_rpm);
void MotorControl_SetRightWheelSpeed(float speed_rpm);   /* right wheel continuous speed (rpm) */
void MotorControl_SetLinearSpeed(float speed_mps);
void MotorControl_MoveTo(int32_t target_position_edges, int32_t max_speed_edges_per_s);
void MotorControl_MoveRelative(int32_t delta_edges, int32_t max_speed_edges_per_s);
void MotorControl_MoveWheelTo(float target_position_rev, float max_speed_rpm);
void MotorControl_MoveWheelRelative(float delta_rev, float max_speed_rpm);
void MotorControl_MoveRightWheelTo(float target_position_rev, float max_speed_rpm);
void MotorControl_MoveRightWheelRelative(float delta_rev, float max_speed_rpm);
void MotorControl_MoveLinearTo(float target_position_m, float max_speed_mps);
void MotorControl_MoveLinearRelative(float delta_m, float max_speed_mps);
float MotorControl_RobotTurnWheelDistanceByDegrees(float angle_deg);
float MotorControl_RobotTurnWheelDistanceByRadians(float angle_rad);
void MotorControl_GetStatus(MotorControlStatus *status);
void MotorControl_GetMotorStatus(MotorSide side, MotorStatus *status);
const char *MotorControl_StateName(MotorState state);
void MotorControl_ClearFault(void);   /* clear sticky nFAULT latch on both wheels */

#ifdef __cplusplus
}
#endif

#endif /* MOTOR_CONTROL_H */
